### ISSUE TITLE
Prepare 0.4 release

### ISSUE THREAD

**Issue by delhomer** [Oslandia/mapillary_classification#63]
The transition between TensorFlow to Keras has meant a lot of changes in the code. Some new features are also available. It is time for releasing!

Steps to do before releasing:
- [x] merge PR #62 
- [x] clean the `deeposlandia` repository (part of PR #64 )
- [x] change the version number in `setup.py` (part of PR #64 )
- [x] read the code to catch some minor formatting issues, useless comments or outdated/missing docstrings (part of PR #64 )
- [x] update `README.md` (part of PR #64 )

**Comment by delhomer** [comment]
@garaud if you think to additional steps, do not hesitate to amend the issue description.

Then I am not really sure to include the hyperparameter optimization in this release. What is your meaning about this question? Maybe we can let it for a 0.4.1... Your opinion is welcome here!

**Comment by garaud** [comment]
We can add hyperparameter optimization in another relase.

The last digit of the semantic versioning, i.e. the `x.y.z` of `z` is often dedicated to fixed bugs. I prefer 0.5 if there are new features.

**Comment by delhomer** [comment]
Ok, I'm fine with that. I modify the issue description accordingly.
